// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onenet-mq.proto

package cn.edu.jxust.sort.mqtt;

/**
 * @author yuanweimin
 * @date 19/09/10 09:34
 * @description
 */
@SuppressWarnings("ALL")
public final class OnenetMq {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_edu_jxust_sort_mqtt_Msg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_edu_jxust_sort_mqtt_Msg_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017onenet-mq.proto\022\035cn.edu.jxust.datadisp" +
                        "lay.mqtt\"5\n\003Msg\022\r\n\005msgid\030\001 \001(\004\022\014\n\004data\030\002" +
                        " \001(\014\022\021\n\ttimestamp\030\003 \001(\004b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_cn_edu_jxust_sort_mqtt_Msg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_edu_jxust_sort_mqtt_Msg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_edu_jxust_sort_mqtt_Msg_descriptor,
                new java.lang.String[]{"Msgid", "Data", "Timestamp",});
    }

    private OnenetMq() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface MsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.edu.jxust.sort.mqtt.Msg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * MQ中该消息的真实id
         * </pre>
         *
         * <code>uint64 msgid = 1;</code>
         */
        long getMsgid();

        /**
         * <pre>
         * 具体的数据
         * </pre>
         *
         * <code>bytes data = 2;</code>
         */
        com.google.protobuf.ByteString getData();

        /**
         * <pre>
         * 精确到ms
         * </pre>
         *
         * <code>uint64 timestamp = 3;</code>
         */
        long getTimestamp();
    }

    /**
     * Protobuf type {@code cn.edu.jxust.sort.mqtt.Msg}
     */
    public static final class Msg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:cn.edu.jxust.sort.mqtt.Msg)
            MsgOrBuilder {
        public static final int MSGID_FIELD_NUMBER = 1;
        public static final int DATA_FIELD_NUMBER = 2;
        public static final int TIMESTAMP_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:cn.edu.jxust.sort.mqtt.Msg)
        private static final cn.edu.jxust.sort.mqtt.OnenetMq.Msg DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Msg>
                PARSER = new com.google.protobuf.AbstractParser<Msg>() {
            @java.lang.Override
            public Msg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Msg(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new cn.edu.jxust.sort.mqtt.OnenetMq.Msg();
        }

        private long msgid_;
        private com.google.protobuf.ByteString data_;
        private long timestamp_;
        private byte memoizedIsInitialized = -1;
        // Use Msg.newBuilder() to construct.
        private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Msg() {
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        private Msg(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            msgid_ = input.readUInt64();
                            break;
                        }
                        case 18: {

                            data_ = input.readBytes();
                            break;
                        }
                        case 24: {

                            timestamp_ = input.readUInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.edu.jxust.sort.mqtt.OnenetMq.internal_static_cn_edu_jxust_sort_mqtt_Msg_descriptor;
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(cn.edu.jxust.sort.mqtt.OnenetMq.Msg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static cn.edu.jxust.sort.mqtt.OnenetMq.Msg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Msg> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.edu.jxust.sort.mqtt.OnenetMq.internal_static_cn_edu_jxust_sort_mqtt_Msg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.edu.jxust.sort.mqtt.OnenetMq.Msg.class, cn.edu.jxust.sort.mqtt.OnenetMq.Msg.Builder.class);
        }

        /**
         * <pre>
         * MQ中该消息的真实id
         * </pre>
         *
         * <code>uint64 msgid = 1;</code>
         */
        public long getMsgid() {
            return msgid_;
        }

        /**
         * <pre>
         * 具体的数据
         * </pre>
         *
         * <code>bytes data = 2;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        /**
         * <pre>
         * 精确到ms
         * </pre>
         *
         * <code>uint64 timestamp = 3;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (msgid_ != 0L) {
                output.writeUInt64(1, msgid_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(2, data_);
            }
            if (timestamp_ != 0L) {
                output.writeUInt64(3, timestamp_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (msgid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, msgid_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, data_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, timestamp_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof cn.edu.jxust.sort.mqtt.OnenetMq.Msg)) {
                return super.equals(obj);
            }
            cn.edu.jxust.sort.mqtt.OnenetMq.Msg other = (cn.edu.jxust.sort.mqtt.OnenetMq.Msg) obj;

            if (getMsgid()
                    != other.getMsgid()) return false;
            if (!getData()
                    .equals(other.getData())) return false;
            if (getTimestamp()
                    != other.getTimestamp()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSGID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getMsgid());
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Msg> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public cn.edu.jxust.sort.mqtt.OnenetMq.Msg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code cn.edu.jxust.sort.mqtt.Msg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.edu.jxust.sort.mqtt.Msg)
                cn.edu.jxust.sort.mqtt.OnenetMq.MsgOrBuilder {
            private long msgid_;
            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            private long timestamp_;

            // Construct using cn.edu.jxust.sort.mqtt.OnenetMq.Msg.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return cn.edu.jxust.sort.mqtt.OnenetMq.internal_static_cn_edu_jxust_sort_mqtt_Msg_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return cn.edu.jxust.sort.mqtt.OnenetMq.internal_static_cn_edu_jxust_sort_mqtt_Msg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                cn.edu.jxust.sort.mqtt.OnenetMq.Msg.class, cn.edu.jxust.sort.mqtt.OnenetMq.Msg.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                msgid_ = 0L;

                data_ = com.google.protobuf.ByteString.EMPTY;

                timestamp_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return cn.edu.jxust.sort.mqtt.OnenetMq.internal_static_cn_edu_jxust_sort_mqtt_Msg_descriptor;
            }

            @java.lang.Override
            public cn.edu.jxust.sort.mqtt.OnenetMq.Msg getDefaultInstanceForType() {
                return cn.edu.jxust.sort.mqtt.OnenetMq.Msg.getDefaultInstance();
            }

            @java.lang.Override
            public cn.edu.jxust.sort.mqtt.OnenetMq.Msg build() {
                cn.edu.jxust.sort.mqtt.OnenetMq.Msg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public cn.edu.jxust.sort.mqtt.OnenetMq.Msg buildPartial() {
                cn.edu.jxust.sort.mqtt.OnenetMq.Msg result = new cn.edu.jxust.sort.mqtt.OnenetMq.Msg(this);
                result.msgid_ = msgid_;
                result.data_ = data_;
                result.timestamp_ = timestamp_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof cn.edu.jxust.sort.mqtt.OnenetMq.Msg) {
                    return mergeFrom((cn.edu.jxust.sort.mqtt.OnenetMq.Msg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(cn.edu.jxust.sort.mqtt.OnenetMq.Msg other) {
                if (other == cn.edu.jxust.sort.mqtt.OnenetMq.Msg.getDefaultInstance()) return this;
                if (other.getMsgid() != 0L) {
                    setMsgid(other.getMsgid());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                cn.edu.jxust.sort.mqtt.OnenetMq.Msg parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (cn.edu.jxust.sort.mqtt.OnenetMq.Msg) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * MQ中该消息的真实id
             * </pre>
             *
             * <code>uint64 msgid = 1;</code>
             */
            public long getMsgid() {
                return msgid_;
            }

            /**
             * <pre>
             * MQ中该消息的真实id
             * </pre>
             *
             * <code>uint64 msgid = 1;</code>
             */
            public Builder setMsgid(long value) {

                msgid_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * MQ中该消息的真实id
             * </pre>
             *
             * <code>uint64 msgid = 1;</code>
             */
            public Builder clearMsgid() {

                msgid_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 具体的数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <pre>
             * 具体的数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 具体的数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 精确到ms
             * </pre>
             *
             * <code>uint64 timestamp = 3;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <pre>
             * 精确到ms
             * </pre>
             *
             * <code>uint64 timestamp = 3;</code>
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 精确到ms
             * </pre>
             *
             * <code>uint64 timestamp = 3;</code>
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:cn.edu.jxust.sort.mqtt.Msg)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
